# -*- coding: utf-8 -*-
"""GovernmentAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CzqYLjLfddbSZhYBVDfrRIDY5wwTMYkM
"""

import requests
from pprint import pprint
import matplotlib.pyplot as plt


def SearchProject(keyword_search='เรือดำน้ำ',year=2562,limit=20):

  url = 'https://opend.data.go.th/govspending/cgdcontract'
  #url = 'https://opend.data.go.th/govspending/summary_cgdcontract'

  token = 'rcdV5Vub9doETaWI798M0sNUCScd0q0O'

  parameters = {'api-key':token, 
                'year':year,
                'keyword':keyword_search,
                'limit':limit
                }

  r = requests.get(url,params=parameters)
  result = r.json()
  print(result)

  allproject = result['result']
  #print(type(allproject))
  print('Count: ',len(allproject)) # len() คือการนับค่าใน List / Dict
  #pprint(allproject[8])

  allbudget = []
  projectname = []

  print('----parameter-----')
  print(allproject[0].keys())
  print('------------------')

  for pj in allproject:
    print(pj['dept_name'])
    print(pj['sum_price_agree'])
    print(pj['project_name'])
    print(pj['transaction_date'])
    allbudget.append(int(pj['sum_price_agree'].replace(',','')))
    projectname.append(pj['project_name'])
    print('---------------')
  print('***************************************************')
  print('ค้นหาคำว่า: {} งบประมาณทั้งหมด: {:,d} บาท'.format(keyword_search,sum(allbudget)))
  print('***************************************************')

  # graph
  # xbar = range(len(projectname))
  # plt.bar(xbar,allbudget)
  # plt.xticks(projectname)
  # plt.show()


SearchProject('หน้ากากอนามัย')

